### ISSUE TITLE
`rand` dependency outdated

### ISSUE THREAD

**Issue by noah04** [caranatar/tracery-rs#10]
The `rand` crate was updated to the major `0.8` version [[1]]. Thus, using `tracery-rs` with `rand::thread_rng` from the new version yields the following compilation error:

```
error[E0277]: the trait bound `ThreadRng: rand_core::RngCore` is not satisfied
 --> src/main.rs:8:36
  |
8 |         .execute(&"origin".into(), &mut rand::thread_rng())
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `ThreadRng`
  |
  = note: required because of the requirements on the impl of `rand::Rng` for `ThreadRng`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

Updating the version in `tracery-rs/Cargo.toml` fixes the issue. Moreover, `cargo test` also runs without any error. 
If you agree that this would be a good solution to solve the issue, I can prepare a Pull Request with the change.

[1]: https://github.com/rust-random/rand/blob/master/CHANGELOG.md#080---2020-12-18

#### Setup
```
$ cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)

$ rustc --version                  
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

#### Cargo.toml
```
[package]
name = "whatever"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
rand = "0.8.3"
tracery = "0.2.0"

```

#### main.rs
```
fn main() {
    let mut g = tracery::grammar! {
        "origin" => "Hello, World!",
    }
    .unwrap();

    let output = g
        .execute(&"origin".into(), &mut rand::thread_rng())
        .unwrap();
    dbg!(output);
}

```

**Comment by caranatar** [comment]
Sorry it took so long, but with the fix from @daniel-tp this should be working again. Going to push a new crate shortly.
